name: Mac Release

on:
  push:
    branches: 
      - 'main'
      - 'continuous-integration'
  pull_request:
    branches: 
      - 'main'
      - 'continuous-integration'

env:
  SOURCE_DIR:   ${{ github.workspace }}  
  QT_VERSION: 6.5.0
  CMAKE_VERSION: 3.21
  ARTIFACT:     task-manager-macos.zip

jobs:
  build:
    runs-on:  macos-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f

      - name: (3) Install Qt
        run: |
          python3 -m venv qt_env
          source qt_env/bin/activate
          python3 -m pip install aqtinstall
          python3 -m aqt install-qt mac desktop 6.5.0 clang_64
          echo "$(pwd)/6.5.0/clang_64/bin" >> $GITHUB_PATH
          echo "Qt6_DIR=$(pwd)/6.5.0/clang_64" >> $GITHUB_ENV

      - name: (4) Create build directory
        run:  mkdir -p ${{ runner.temp }}/build

      - name: (5) Configure CMake
        working-directory: ${{ runner.temp }}/build
        run: 
          cmake ${{ env.SOURCE_DIR }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ runner.workspace }}/Qt/6.5.0/clang_64"

      - name: (5) Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build --parallel 2

      - name: (7) Deploy Qt dependencies
        working-directory: ${{ runner.temp }}/build
        run:  |
              # Find the built executable (adjust path as needed for your CMake setup)
              find . -name "*.app" -type d | head -1 | xargs -I {} macdeployqt {} -qmldir=${{ env.SOURCE_DIR }} -dmg
              
      - name: (8) Zip build artifacts
        working-directory: ${{ runner.temp }}/build
        run:  |
              zip -r ../task-manager-macos.zip *.app *.dmg
              
      - name: (9) Save build artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT }}