name: Mac Release

on:
  push:
    branches: 
      - 'main'
      - 'continuous-integration'
  pull_request:
    branches: 
      - 'main'
      - 'continuous-integration'

env:
  SOURCE_DIR:   ${{ github.workspace }}  
  QT_VERSION: 6.5.0
  CMAKE_VERSION: 3.21
  ARTIFACT:     task-manager-macos.zip

jobs:
  build:
    runs-on:  macos-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f

      - name: (3) Install Qt via Homebrew
        run: |
          brew install qt@6
          echo "Qt6_DIR=$(brew --prefix qt@6)/lib/cmake/Qt6" >> $GITHUB_ENV

      - name: (4) Create build directory
        run: mkdir -p ${{ runner.temp }}/build


      - name: (5) Configure CMake
        working-directory: ${{ runner.temp }}/build
        run: |
          cmake ${{ env.SOURCE_DIR }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6)" \
            -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
            -DCMAKE_MACOSX_RPATH=ON \
            -DCMAKE_INSTALL_RPATH="@executable_path/../Frameworks;$(brew --prefix qt@6)/lib"

      - name: (6) Build
        working-directory: ${{ runner.temp }}/build
        run: cmake --build . --parallel 2

      - name: (7) Create DMG
        working-directory: ${{ runner.temp }}/build
        run: |
          APP_PATH=$(find . -name "*.app" -type d | head -1)
          echo "Found app: $APP_PATH"
          
          # Find the main executable
          EXECUTABLE=$(find "$APP_PATH/Contents/MacOS" -type f -perm +111 | head -1)
          echo "Main executable: $EXECUTABLE"
          
          # Fix rpath for the executable
          if [ -n "$EXECUTABLE" ]; then
            install_name_tool -add_rpath "$(brew --prefix qt@6)/lib" "$EXECUTABLE" || true
            install_name_tool -add_rpath "@executable_path/../Frameworks" "$EXECUTABLE" || true
          fi
          
          # Deploy
          "$(brew --prefix qt@6)/bin/macdeployqt" "$APP_PATH" \
            -qmldir="${{ env.SOURCE_DIR }}" \
            -libpath="$(brew --prefix qt@6)/lib" \
            -dmg \
            -verbose=2

      - name: (8) Zip build artifacts
        working-directory: ${{ runner.temp }}/build
        run:  |
              zip -r ../task-manager-macos.zip *.app *.dmg
              
      - name: (9) Save build artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT }}